Action to take infos regarding resources created by a run
redhat-developer/intellij-tekton pull request #224
Opened 2020-09-21 14:55 UTC by lstocchi

It resolves #181 

This is the first implementation of an action which should be useful to debug a *run. 
As an example, i created a pvc with a size which wasn't supported by my cluster (there was no pv available for that size) and so the *run could not be completed but it was stuck in a running mode. 
By using the tkn cli the user doesn't receive any feedback in such cases.
By clicking on the `Show Diagnostic Data` action this is the result. 
![image](https://user-images.githubusercontent.com/49404737/93781956-42eee580-fc2a-11ea-81c1-4dd34274fd94.png)

I'll try to add more examples as soon as i find them. Any other suggestion for this? @jeffmaury

2020-09-24 15:39 UTC, jeffmaury requested changes
I had a couple of issues:

- it turns out that for a reason I ignore, I have pipelineruns in my cluster with no associated pods or statefulsets thus the generated string is empty. We should not open a terminal in this case but rather report to the user that no data was extracted.
- launching echo on Windows does not work because it's not a process so I think the correct way to do it is to launch cmd.exe /C echo xxxx

2020-09-29 16:17 UTC, lstocchi commented
Changed it based on your comment. Now a warning popup is displayed if no data is found.
For the windows command i don't have idea if it works, just let me know.

2020-10-06 20:56 UTC, lstocchi commented
@jeffmaury is this ready?

2020-10-07 06:13 UTC, jeffmaury commented
Yes but needs a rebase.

2020-10-07 09:10 UTC, merged