report user for invalid runAfter section in finally (#285)
redhat-developer/intellij-tekton pull request #303
Opened 2020-12-15 09:12 UTC by lstocchi

it resolves #285 

![image](https://user-images.githubusercontent.com/49404737/102194802-04319a00-3ebe-11eb-9e7d-a8b22c94456a.png)

2020-12-15 17:25 UTC, jeffmaury requested changes

2020-12-15 17:25 UTC, jeffmaury commented on src/main/java/com/redhat/devtools/intellij/tektoncd/ui/inspector/VariableReferencesInspector.java
> +package com.redhat.devtools.intellij.tektoncd.ui.inspector;
An inspector is a background task and is not part of ui in an MVC word so would be better moved to another package

2020-12-15 17:25 UTC, jeffmaury commented on src/test/java/com/redhat/devtools/intellij/tektoncd/ui/inspector/FinallyReferencesInspectorTest.java
> +package com.redhat.devtools.intellij.tektoncd.ui.inspector;
Same remark

2020-12-16 18:41 UTC, jeffmaury requested changes

2020-12-16 18:41 UTC, jeffmaury commented on src/test/java/com/redhat/devtools/intellij/tektoncd/ui/inspector/FinallyReferencesInspectorTest.java
> +package com.redhat.devtools.intellij.tektoncd.ui.inspector;
i see it still in a ui package

2020-12-16 18:41 UTC, jeffmaury commented on src/test/java/com/redhat/devtools/intellij/tektoncd/ui/inspector/VariableReferenceInspectorTest.java
> +package com.redhat.devtools.intellij.tektoncd.ui.inspector;
Same remark

2020-12-16 18:41 UTC, jeffmaury commented on src/test/resources/ui/inspector/finallyReferencesInspector/pipeline1.yaml
> +apiVersion: tekton.dev/v1beta1
Same remark

2020-12-16 22:53 UTC, lstocchi commented
@jeffmaury sorry, i completely forgot the tests :/

2020-12-17 08:13 UTC, jeffmaury approved these changes
LGTM

2020-12-17 08:17 UTC, merged