Generate taskrun example from task (#289)
redhat-developer/intellij-tekton pull request #305
Opened 2020-12-17 12:27 UTC by lstocchi

it resolves #289

2020-12-18 12:53 UTC, jeffmaury requested changes
Tested on task aws-cli from Hub but found issues with workspaces:
EmptyDir: "{}"

Should be:
emptyDir: {}

2021-01-04 08:48 UTC, jeffmaury requested changes
Still have `EmptyDir` instead of `emptyDir`:

![image](https://user-images.githubusercontent.com/695993/103517109-e8446700-4e71-11eb-900b-84ab5c6b57e8.png)

2021-01-04 09:29 UTC, lstocchi commented
> Still have `EmptyDir` instead of `emptyDir`:

I completely missed the name was wrong. Fixed for all workspace kinds

2021-01-05 07:42 UTC, jeffmaury approved these changes

2021-01-05 08:34 UTC, merged