Add setting to show logs in editor
redhat-developer/intellij-tekton pull request #318
Opened 2021-01-11 09:06 UTC by lstocchi

it resolves #262

2021-01-22 15:28 UTC, jeffmaury requested changes
I think there a some part if this change that is not specific to Tekton (`openInEditor`) so it should go into intellij-tekton

2021-01-22 15:28 UTC, jeffmaury commented on src/main/java/com/redhat/devtools/intellij/tektoncd/tkn/TknCli.java
> +            executeWithEditor(namespace + "-" + pipelineRun + ".log", envVars, command, "pipelinerun", "logs", pipelineRun, "-n", namespace);
Not sure if this can happen but without a qualifier you will face collision between taskruns and pipelineruns

2021-01-27 11:27 UTC, lstocchi commented
@jeffmaury refactored based on your comments. You can find the intellij-common PR here -> https://github.com/redhat-developer/intellij-common/pull/30

2021-02-02 12:19 UTC, jeffmaury approved these changes

2021-02-02 13:16 UTC, merged