Add workflow to create changelog and plugin archive when new tag is created
redhat-developer/intellij-tekton pull request #335
Opened 2021-02-08 11:54 UTC by lstocchi

Output sample https://github.com/lstocchi/intellij-tekton/releases/tag/0.0.81

2021-02-23 15:33 UTC, jeffmaury requested changes
Also I tried it on my repo but got an error: see https://github.com/jeffmaury/intellij-tekton/runs/1962419062?check_suite_focus=true

2021-02-23 15:33 UTC, jeffmaury commented on .github/workflows/tag.yml
> +      - name: Attach vsix to release
Should be Attach zip to release

2021-02-23 16:20 UTC, lstocchi commented
> Also I tried it on my repo but got an error: see https://github.com/jeffmaury/intellij-tekton/runs/1962419062?check_suite_focus=true

I think it fails bc there is only 1 tag. The action should take the last tag + the previous and take all commits between them. I guess it misses the logic for when there is only 1 tag. I'll look into it but if you try by creating a new tag it should work.

2021-02-23 17:46 UTC, jeffmaury commented
Adding a new tag but still failing: https://github.com/jeffmaury/intellij-tekton/runs/1963486856?check_suite_focus=true

So giving up and reviewing based on your sample. LGTM but Features paragraph should be first, not after Bug Fixes ?

2021-02-24 09:01 UTC, lstocchi commented
Checked the code. In the function to retrieve all valid tags, it filters by checking if the version is semver valid
`const releaseTags = tags.filter((tag) => compareVersions.validate(tag.name));`

the validate does this 
```
/**
   * Validate [semver](https://semver.org/) version strings.
   * 
   * @param version Version number to validate
   * @returns `true` if the version number is a valid semver version number, `false` otherwise.
   *
   * @example
   * ```
   * compareVersions.validate('1.0.0-rc.1'); // return true
   * compareVersions.validate('1.0-rc.1'); // return false
   * compareVersions.validate('foo'); // return false
   * ```
   */
```

as you are using invalid semver version it fails.

2021-02-24 09:05 UTC, jeffmaury commented
OK got it as I was using vx.x as tag names !!!!

2021-02-24 09:07 UTC, lstocchi commented
The order of the sections depend on the commits history right now. The fix was first bc the first commit retrieved from gh was a fix. I'll change that by using the order found in the workflow when we specify the types used. So if we have [feat, fix, docs] the sections will be showed in this order.

2021-02-24 10:57 UTC, lstocchi commented
Update action with new section ordering. 
Example here https://github.com/lstocchi/intellij-tekton/releases/tag/0.0.82

2021-02-24 11:09 UTC, jeffmaury approved these changes
LGTM. Maybe rename as release.yml, looks more natural for novice users landing on the project

2021-02-24 11:28 UTC, lstocchi commented
@jeffmaury Ok, should i also add a section to the documentation that explain this?

2021-02-24 12:25 UTC, jeffmaury commented
I think the only thing to document is the conventional commits so should go into CONTRIBUTING.md

2021-03-02 09:00 UTC, merged