chore(skip-release): prepare 1.0.0
redhat-developer/intellij-tekton pull request #505
Opened 2021-11-23 14:13 UTC by lstocchi

Signed-off-by: Luca Stocchi <lstocchi@redhat.com>

2021-11-23 14:16 UTC, jeffmaury approved these changes
LGTM. Asking @mohitsuman to approve as well before we publish

2021-11-23 17:36 UTC, mohitsuman requested changes

2021-11-23 17:36 UTC, mohitsuman commented on README.md
> +To use the debug feature you must have access to a kubernetes or openshift cluster with Tekton installed with a version
```suggestion
To use the debug feature, you must have access to a Kubernetes or OpenShift cluster with Tekton installed with a version 
```

2021-11-23 20:20 UTC, mohitsuman approved these changes

2021-11-24 08:05 UTC, mohitsuman requested changes

2021-11-24 08:05 UTC, mohitsuman commented on README.md
>  This new release is based on v1beta1. Although it still supports v1alpha1 resources (resources, conditions), we do not support v1alpha1 version for resources that have v1beta1.
```suggestion
We support `v1beta1` API. Previous version `v1alpha1` may work, but we cannot guarantee that all features will work properly. If you have `v1alpha1` pipelines/tasks please use [migrating document](https://github.com/tektoncd/pipeline/blob/main/docs/migrating-v1alpha1-to-v1beta1.md) to migrate to `v1beta1`.
```

2021-11-24 08:05 UTC, mohitsuman commented on README.md
>  This new release is based on v1beta1. Although it still supports v1alpha1 resources (resources, conditions), we do not support v1alpha1 version for resources that have v1beta1.
@lstocchi This is to make it consistent with the information we have in VSCode tekton.

2021-11-24 08:25 UTC, mohitsuman approved these changes

2021-11-24 08:51 UTC, merged