feat: add getting started page (#586)
redhat-developer/intellij-tekton pull request #603
Opened 2022-08-23 16:22 UTC by lstocchi

it resolves #586

2022-09-06 07:25 UTC, jeffmaury approved these changes
LGTM

2022-11-15 10:27 UTC, lstocchi commented
@mohitsuman I tried to tweak the settings of my recording tool and also increased the IJ IDE font, this is the best quality i could achieve for the gifs, give it a look please. Thanks!!

2022-11-15 21:31 UTC, mohitsuman commented on src/main/java/com/redhat/devtools/intellij/tektoncd/ui/toolwindow/GettingStartedToolWindow.java
> +                        "any Tekton resource by using the IDE editor.</p>" +
```suggestion
                        "any Tekton resource directly from the IDE.</p>" +
```

2022-11-15 21:31 UTC, mohitsuman commented on src/main/java/com/redhat/devtools/intellij/tektoncd/ui/toolwindow/GettingStartedToolWindow.java
> +                        "<p>By executing the `New <resource>` action a new editor tab opens up with a snippet " +
```suggestion
                        "<p>By executing the `New <resource>` action, a new editor tab opens up with a snippet " +
```

2022-11-15 21:32 UTC, mohitsuman commented on src/main/java/com/redhat/devtools/intellij/tektoncd/ui/toolwindow/GettingStartedToolWindow.java
> +                        "Once you have done editing it, click the Push action in the top toolbar or in the " +
```suggestion
                        "Once you are done with the editing, click the Push action in the top toolbar or in the " +
```

2022-11-15 21:32 UTC, mohitsuman commented on src/main/java/com/redhat/devtools/intellij/tektoncd/ui/toolwindow/GettingStartedToolWindow.java
> +                "Start a pipeline/task",
```suggestion
                "Start a Pipeline/Task",
```

2022-11-15 21:33 UTC, mohitsuman commented on src/main/java/com/redhat/devtools/intellij/tektoncd/ui/toolwindow/GettingStartedToolWindow.java
> +                        "get it started (params, workspaces, service accounts, ..). " +
```suggestion
                        "get it started (params, workspaces, service accounts). " +
```

2022-11-15 21:34 UTC, mohitsuman commented on src/main/java/com/redhat/devtools/intellij/tektoncd/ui/toolwindow/GettingStartedToolWindow.java
> +                        "<p>N.B: By default if the pipeline/task has no inputs, it will get started directly " +
```suggestion
                        "<p>Note: By default, the pipeline/task gets started directly if it has no inputs. " +
```

2022-11-15 21:35 UTC, mohitsuman commented on src/main/java/com/redhat/devtools/intellij/tektoncd/ui/toolwindow/GettingStartedToolWindow.java
> +                        "<p>If you already run a pipeline/task earlier and wants to run it again with the same inputs " +
```suggestion
                        "<p>If you have already run a pipeline/task earlier and want to run it again with the same inputs " +
```

2022-11-15 21:36 UTC, mohitsuman commented on src/main/java/com/redhat/devtools/intellij/tektoncd/ui/toolwindow/GettingStartedToolWindow.java
> +                        "<p>Opposite, if you want to start a pipeline/task with the same inputs of a specific old run " +
```suggestion
                        "<p>And similarly, if you want to start a pipeline/task with the same inputs of a specific old run " +
```

2022-11-15 21:38 UTC, mohitsuman commented on src/main/java/com/redhat/devtools/intellij/tektoncd/ui/toolwindow/GettingStartedToolWindow.java
> +                "<html><p>When a task fails its execution and looking at the logs it is not enough to identify " +
```suggestion
                "<html><p>When a task fails its execution and the logs are not enough to identify " +
```

2022-11-15 21:39 UTC, mohitsuman commented on src/main/java/com/redhat/devtools/intellij/tektoncd/ui/toolwindow/GettingStartedToolWindow.java
> +                        "the issue, you can think at starting it in debug mode. This way the container where the taskrun " +
```suggestion
                        "the issue, you can start it in debug mode. This way the container where the taskrun " +
```

2022-11-15 21:40 UTC, mohitsuman commented on src/main/java/com/redhat/devtools/intellij/tektoncd/ui/toolwindow/GettingStartedToolWindow.java
> +                        "workspaces and resources of a task without typing them by hand.</p>" +
```suggestion
                        "workspaces and resources of a task automatically.</p>" +
```

2022-11-15 21:41 UTC, mohitsuman commented on src/main/java/com/redhat/devtools/intellij/tektoncd/ui/toolwindow/GettingStartedToolWindow.java
> +                "Creating or editing a Tekton resource is made easier",
```suggestion
                "Creating or Editing a Tekton resource is made easier",
```

2022-11-15 21:42 UTC, mohitsuman requested changes
Added comments around the wordings. The gifs looks good and clear.

2022-11-16 09:50 UTC, lstocchi commented
@mohitsuman Done, Thanks!!

2022-11-16 11:48 UTC, mohitsuman approved these changes
LGTM

2022-11-16 11:55 UTC, merged