chore: prepare 1.4.3 release and deprecate project
redhat-developer/intellij-tekton pull request #675
Opened 2024-09-24 14:29 UTC by sbouchet

fixes #674

2024-09-24 19:24 UTC, mohitsuman commented on README.md
> +## NOTE: This project is no more maintained and marked as deprecated.
```suggestion
## NOTE: This plugin is no longer maintained and is officially deprecated.
```

2024-09-24 19:25 UTC, mohitsuman commented on src/main/resources/META-INF/plugin.xml
>    <vendor email="developers@redhat.com" url="https://www.redhat.com">Red-Hat</vendor>
```suggestion
  <vendor email="devtools-team@redhat.com" url="https://www.redhat.com">Red-Hat</vendor>
```

2024-09-24 19:26 UTC, mohitsuman commented on src/main/resources/META-INF/plugin.xml
>    <vendor email="developers@redhat.com" url="https://www.redhat.com">Red-Hat</vendor>
I think having the devtools-team email is more useful than having developers@redhat.com (as this thing does not exist)

2024-09-24 19:28 UTC, mohitsuman commented on src/main/resources/META-INF/plugin.xml
> +    <li>Update Schemas tto Tekton Pipelines 0.56.0 and Triggers to 0.26.0</li>
```suggestion
    <li>Update Schemas to Tekton Pipelines 0.56.0 and Tekton Triggers to 0.26.0</li>
```

2024-09-24 19:29 UTC, mohitsuman commented on src/main/resources/META-INF/plugin.xml
> +    <li>This extension is now deprecated.</li>
We do not need this line as we are mentioning at the top this plugin is deprecated.

2024-09-24 19:29 UTC, mohitsuman requested changes
wording updates

2024-09-25 12:43 UTC, sbouchet commented
@mohitsuman 
fix reviews. please re-review.

2024-09-26 09:30 UTC, adietish approved these changes

2024-09-26 12:19 UTC, mohitsuman approved these changes
lgtm

2024-09-26 13:21 UTC, merged